--- #YAML:1.0
name:                SemanticWeb-OAI-ORE
version:             0.94
abstract:            Modules to read/write/modify OAI-ORE resource maps
license:             ~
author:              
    - Simeon Warner <simeon@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Algorithm::Diff:               0
    Class::Accessor:               0
    Data::UUID:                    0
    DateTime:                      0
    RDF::Core:                     0.51
    RDF::Core::Model:              0
    RDF::Notation3:                0.91
    RDF::Notation3::RDFCore:       0
    Test::More:                    0
    XML::Atom::Syndication:        0.942
    XML::Atom::Syndication::Writer: 0
    XML::Writer:                   0.611
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
