---
abstract: 'Modules to read/write/modify OAI-ORE resource maps'
author:
  - 'Simeon Warner <simeon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.7301, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SemanticWeb-OAI-ORE
no_index:
  directory:
    - t
    - inc
requires:
  Algorithm::Diff: 1.1902
  Class::Accessor: 0.34
  Data::UUID: 1.2
  DateTime: 0.5
  RDF::Core: 0.51
  RDF::Core::Model: 0
  RDF::Notation3: 0.91
  RDF::Notation3::RDFCore: 0
  Test::More: 0.94
  XML::Atom::Syndication: 0.942
  XML::Atom::Syndication::Writer: 0
  XML::Writer: 0.611
version: 1.00
